# Generated by Django 5.0.4 on 2024-08-16 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_p', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='nom',
            new_name='username',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='sexe',
            field=models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin'), ('X', 'Non-spécifié')], default='X', max_length=1),
        ),
    ]
