# Generated by Django 5.0.4 on 2024-08-16 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_p', '0002_rename_nom_utilisateur_username_utilisateur_sexe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='mot_de_passe',
            new_name='password',
        ),
    ]
