# Generated by Django 5.0.4 on 2024-09-10 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page_p', '0006_patient_rendezvous'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rendezvous',
            name='duree',
        ),
    ]
