# Generated by Django 5.0.4 on 2024-09-11 04:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_p', '0008_alter_rendezvous_medecin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_p.patient'),
        ),
    ]
