# Generated by Django 5.0.4 on 2024-09-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_p', '0009_alter_rendezvous_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='annule',
            field=models.BooleanField(default=False),
        ),
    ]
