# Generated by Django 5.0.4 on 2024-09-11 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_p', '0010_rendezvous_annule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='annule',
            field=models.BooleanField(default=False, verbose_name='Annulé'),
        ),
    ]
