# Generated by Django 5.0.4 on 2024-09-12 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_p', '0011_alter_rendezvous_annule'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostics', models.TextField()),
                ('traitements', models.TextField()),
                ('parametre', models.TextField()),
                ('symptome', models.TextField()),
                ('resultatsexamen', models.TextField()),
                ('patient', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_p.patient')),
            ],
        ),
    ]
