# Generated by Django 5.0.4 on 2024-09-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_p', '0012_dossiermedical'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dossiermedical',
            name='resultatsexamen',
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='resultats_examen',
            field=models.TextField(blank=True, null=True),
        ),
    ]
