# Generated by Django 5.0.4 on 2024-09-15 06:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_p', '0013_remove_dossiermedical_resultatsexamen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dossiermedical',
            name='data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dossiermedical',
            name='encryption_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dossiermedical',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page_p.patient'),
        ),
    ]
